name: rs-test

on:
  pull_request:
    branches: [ "main" ]
  
env:
  CARGO_TERM_COLOR: always

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: |
        cargo install cargo2junit;
        cargo test -- -Z unstable-options --format json | cargo2junit > results.xml
    - name: Report
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Results
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: results.xml